// packages/core/src/config/loader.ts
// YAML config file loader with ${ENV_VAR} interpolation

import * as fs from 'node:fs';
import * as path from 'node:path';
import { ConfigError } from '../errors.js';
import { applyEnvOverrides } from './env-overrides.js';
import { interpolateConfig, interpolateEnvValue, type ConfigWarning } from './interpolate.js';
import { mergeDefaults } from './merge.js';
import { parseYamlObject } from './parse.js';
import { ConfigSchema, type DevLoopConfig } from './schema.js';
import { writeYamlFile } from './writer.js';

export { applyEnvOverrides } from './env-overrides.js';
export { mergeDefaults } from './merge.js';
export type { ConfigWarning } from './interpolate.js';

export interface LoadConfigOptions {
  projectDir?: string;
  configPath?: string;
  env?: NodeJS.ProcessEnv;
  onWarning?: (warning: ConfigWarning) => void;
  invalidConfig?: 'throw' | 'warn-and-default';
}

/** Interpolate ${ENV_VAR} references in a string value */
export function interpolateEnv(value: string): string {
  return interpolateEnvValue(value, {
    env: process.env,
    onWarning: warning => console.warn(`dev-loop: ${warning.message}`),
  });
}

function parseYamlConfig(rawContent: string): Record<string, unknown> {
  return parseYamlObject(rawContent);
}

/** Load and validate dev-loop.yaml configuration from the given directory */
export async function loadConfig(
  optionsOrProjectDir: LoadConfigOptions | string = {},
  legacyConfigPath?: string,
): Promise<DevLoopConfig> {
  const options: LoadConfigOptions = typeof optionsOrProjectDir === 'string'
    ? { projectDir: optionsOrProjectDir, configPath: legacyConfigPath, invalidConfig: 'warn-and-default' }
    : optionsOrProjectDir;
  const projectDir = options.projectDir ?? process.cwd();
  const filePath = options.configPath ?? path.join(projectDir, 'dev-loop.yaml');
  const env = options.env ?? process.env;
  const invalidConfig = options.invalidConfig ?? 'throw';

  if (!fs.existsSync(filePath)) {
    return ConfigSchema.parse({});
  }

  const rawContent = fs.readFileSync(filePath, 'utf-8');
  const parsed = parseYamlObject(rawContent);
  const interpolated = interpolateConfig(parsed, {
    env,
    onWarning: options.onWarning,
  }) as Record<string, unknown>;

  const merged = mergeDefaults(ConfigSchema.parse({}), interpolated);
  const withEnv = applyEnvOverrides(merged, { env });
  const validated = ConfigSchema.safeParse(withEnv);

  if (validated.success) return validated.data;

  if (invalidConfig === 'warn-and-default') {
    options.onWarning?.({
      code: 'config.validation.failed',
      message: 'Config validation failed; defaults were used.',
      details: validated.error.errors,
    });
    return ConfigSchema.parse({});
  }

  throw new ConfigError(
    'dev-loop.yaml failed validation.',
    'Fix the reported config keys and run the command again.',
    { issues: validated.error.errors },
  );
}

/** Create a default dev-loop.yaml config file if it doesn't exist */
export async function createDefaultConfig(projectDir: string): Promise<string> {
  const configPath = path.join(projectDir, 'dev-loop.yaml');

  if (fs.existsSync(configPath)) {
    return configPath;
  }

  const defaultContent = `# dev-loop configuration
# Generated by dev-loop init

version: "1"

planning:
  primary:
    provider: anthropic
    model: claude-sonnet-4-6
    api_key: \${ANTHROPIC_API_KEY}
    temperature: 0.3
    max_tokens: 8192
  auto_select: false
  scoring: true

coding:
  primary:
    provider: auto
    model: auto
    temperature: 0.2
    max_tokens: 16384
  auto_select:
    enabled: true
    prefer_local: true
    prefer_cheapest: true
    prefer_fastest: true
    max_cost_per_1k_tokens: 0.002
    auto_switch_on_repeated_failure: true
    failure_threshold: 2
    notify_on_switch: true
    auto_confirm_switch: false
  warm_state: true
  warmup_prompt: true

verifier:
  provider: claude-code-cli
  model: claude-sonnet-4-6
  effort:
    default: medium
    auto_adjust: true
  confidence_score:
    enabled: true
    notify_below: 0.7
  asymmetric:
    enabled: true
    risk_threshold: 0.4
    cheap_verifier: codex-cli
    expensive_verifier: claude-code-cli

fallback:
  provider: claude-code-cli
  effort: high
  max_attempts: 1

loop:
  max_retry: 5
  retry_delay_seconds: 2
  diff_aware: true
  sandbox_mode: true
  checkpoint: true
  smart_retry: true
  incremental_testing: true
  idempotency_check: true
  cost_budget_usd: 5.00
  time_budget_minutes: 60
  warmup_prompt: true
  conversation_memory: true
  uncertain_tag: "TODO:UNCERTAIN"
  uncertain_notify: true
  auto_rollback: true

test_runner:
  type: command
  command: pytest
  args: ["-v", "--tb=short"]
  timeout_seconds: 300

quality_gate:
  enabled: true
  block_commit_on_failure: true
  checks:
    test_coverage_min: 80
    complexity_max: 10
    secrets: true
    vulnerabilities: true
    mcp_score_min: 0
    uncertain_tags: true
    lint: true
    type_coverage_min: 0

mcp:
  enabled: true
  injection_detection: true
  servers: []

context:
  code_map: true
  decisions: true
  patterns: true
  semantic_search: true
  token_cache: true
  max_context_tokens: 100000

learning:
  error_patterns:
    enabled: true
    threshold: 1
    auto_inject: true
    versioned: true
  success_patterns:
    enabled: true
  model_calibration:
    enabled: true
    track_time_of_day: true
    track_feature_type: true
    track_language: true

notifications:
  desktop:
    enabled: true
    events: [success, failure]

git:
  auto_commit: true
  commit_prefix: feat
  commit_message_template: "{prefix}: {feature_summary}"
  sign_commits: false
  auto_changelog: true
  semantic_versioning: true

agents:
  supervisor: true
  specialized:
    planning: false
    testing: false
    refactoring: false
    documentation: false
    security: false

ui:
  port: 3747
  host: localhost
  open_browser: true
  theme: dark
  real_time_updates: true

observability:
  anomaly_detection: true
  sla_minutes: 0
  trend_analysis: true
  natural_language_queries: true
`;

  fs.writeFileSync(configPath, defaultContent, 'utf-8');
  return configPath;
}

/** Write updated config values back to dev-loop.yaml */
export async function saveConfig(
  projectDir: string = process.cwd(),
  updates: Record<string, unknown>,
): Promise<void> {
  const configPath = path.join(projectDir, 'dev-loop.yaml');
  const rawExisting = fs.existsSync(configPath)
    ? parseYamlConfig(fs.readFileSync(configPath, 'utf-8'))
    : {};
  const base = mergeDefaults(ConfigSchema.parse({}), rawExisting);
  const merged = mergeDefaults(base, updates);
  const validated = ConfigSchema.parse(merged);

  writeYamlFile(configPath, validated);
}
