import { existsSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'; import { tmpdir } from 'node:os'; import path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest'; import { processVoiceInput } from '../analytics/voice.js';
const dirs: string[] = []; afterEach(() => dirs.splice(0).forEach(dir => rmSync(dir, { recursive: true, force: true })));
describe('FEATURE121 production voice input', () => {
  it('bounds file input, confirms, and calls the configured transcriber', async () => { const dir = mkdtempSync(path.join(tmpdir(), 'voice-')); dirs.push(dir); const file = path.join(dir, 'voice.wav'); writeFileSync(file, 'audio'); const transcribe = vi.fn(async () => ({ text: '  çalıştır  ', language: 'tr' })); await expect(processVoiceInput({ enabled: true, file, maxBytes: 10, confirm: async () => true, transcriber: { transcribe } })).resolves.toEqual({ text: 'çalıştır', language: 'tr', source: 'file', bytes: 5, confirmed: true }); expect(transcribe).toHaveBeenCalledOnce(); expect(existsSync(file)).toBe(true); });
  it('does not transcribe without explicit confirmation', async () => { const dir = mkdtempSync(path.join(tmpdir(), 'voice-')); dirs.push(dir); const file = path.join(dir, 'voice.wav'); writeFileSync(file, 'audio'); const transcribe = vi.fn(); await expect(processVoiceInput({ enabled: true, file, confirm: () => false, transcriber: { transcribe } })).rejects.toThrow('cancelled'); expect(transcribe).not.toHaveBeenCalled(); });
  it('rejects oversized audio before provider calls', async () => { const dir = mkdtempSync(path.join(tmpdir(), 'voice-')); dirs.push(dir); const file = path.join(dir, 'voice.wav'); writeFileSync(file, 'audio'); const transcribe = vi.fn(); await expect(processVoiceInput({ enabled: true, file, maxBytes: 2, confirm: () => true, transcriber: { transcribe } })).rejects.toThrow('limit'); expect(transcribe).not.toHaveBeenCalled(); });
  it('cleans recorded temporary audio on provider failure', async () => { const dir = mkdtempSync(path.join(tmpdir(), 'voice-')); dirs.push(dir); const file = path.join(dir, 'recording.wav'); writeFileSync(file, 'audio'); await expect(processVoiceInput({ enabled: true, record: async () => ({ file, temporary: true }), confirm: () => true, transcriber: { transcribe: async () => { throw new Error('provider failed'); } } })).rejects.toThrow(); expect(existsSync(file)).toBe(false); });
});
